---
# Source: oci-native-ingress-controller/templates/serviceaccount.yaml
#
# OCI Native Ingress Controller
#
# Copyright (c) 2023 Oracle America, Inc. and its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oci-native-ingress-controller
  namespace: native-ingress-controller-system
  labels:
    helm.sh/chart: oci-native-ingress-controller-1.3.3
    app.kubernetes.io/name: oci-native-ingress-controller
    app.kubernetes.io/instance: oci-native-ingress-controller
    app.kubernetes.io/version: "1.3.3"
    app.kubernetes.io/managed-by: Helm
